version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test_user
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
      PG_TRUST_LOCALNET: 'true'
    ports:
      - "54322:5432"
    volumes:
      - ./model.sql:/docker-entrypoint-initdb.d/model.sql